name: Android CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: touch local.properties
      env:
        MARVEL_PRIVATE_KEY: ${{ secrets.MARVEL_PRIVATE_KEY }}
        MARVEL_PUBLIC_KEY: ${{ secrets.MARVEL_PUBLIC_KEY }}
      run: echo -e "marvel_private_key ="$MARVEL_PRIVATE_KEY"\nmarvel_public_key = "$MARVEL_PUBLIC_KEY"" > ./local.properties
      
    - name: Build with Gradle
      run: ./gradlew build
