name: PR - Code builder

on:
  pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: touch local.properties
        env:
          MARVEL_PRIVATE_KEY: ${{ secrets.MARVEL_PRIVATE_KEY }}
          MARVEL_PUBLIC_KEY: ${{ secrets.MARVEL_PUBLIC_KEY }}
        run: echo -e "marvel_private_key ="$MARVEL_PRIVATE_KEY"\nmarvel_public_key = "$MARVEL_PUBLIC_KEY"" > ./local.properties

      - name: Build Clean
        run: bash ./gradlew clean build

      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Build Unit Test
        run: bash ./gradlew test
       
